### ISSUE TITLE
4 - Events

### ISSUE THREAD

**Issue by kevinkidwell** [cul-it/uls#184] opened 2019-03-27 12:40 UTC
Priority: 4
Feature: Events

This epic will contain all issues pertaining to events, including how they will be aggregated and displayed from multiple sources. 

**Notes:**
Events research: All relevant information for events feature that will need to be considered.

Phase 1 (by Oct 2019):
Display a styled list from an RSS feed
Aggregate multiple feeds and remove duplicates

Phase 2:
Add filtering by type, date, and location
Add calendar view

Feed Sources:
LibCal
Localist
R25 - migrating to 25Live in Fall 2019
https://johnson.campusgroups.com/mgmtlibrary/rss_calendar

**Comment by kevinkidwell** [comment] 2019-07-03 14:38
We can use the same WP RSS Aggregator as New Books to be able to do this.

**Comment by cappadona** [comment] 2020-07-20 14:32
Duplicate of #661

**Closed** 2020-09-22 13:25 UTC
Labels: Epic, duplicate
